<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'c9a67d447fa4b0141ade47c984dd4d9d' => $baseDir . '/init/OrionServiceInit.php',
);
