<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'cb4e5a3b92883c2abbbd5cf62df19cae' => $baseDir . '/init/DBServiceInit.php',
);
