<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '5ae53621e4e2e0c9be34cfcf43f58c60' => $baseDir . '/init/FBMoudleInit.php',
);
