<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc476e875cc2878bc5a0d474de6f46677
{
    public static $files = array (
        'c9a67d447fa4b0141ade47c984dd4d9d' => __DIR__ . '/../..' . '/init/OrionServiceInit.php',
    );

    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OrionService\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OrionService\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc476e875cc2878bc5a0d474de6f46677::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc476e875cc2878bc5a0d474de6f46677::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
