<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2f153e0f0cb90e97d069911b5b182832
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'FacebookAds\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'FacebookAds\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/php-ads-sdk/src/FacebookAds',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2f153e0f0cb90e97d069911b5b182832::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2f153e0f0cb90e97d069911b5b182832::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
