<?php
/**
 * Created by IntelliJ IDEA.
 * User: Feng
 * Date: 2017/12/26
 * Time: 上午10:08
 */

namespace FBBasicService\Constant;


class TargetingConstant
{
    const GENDER_MALE = 1;
    const GENDER_FEMALE = 2;

    const AGE_MAX_LIMIT = 65;
    const AGE_MIN_LIMIT = 13;
    const AGE_MIN_DEFAULT = 18;
    const AGE_MAX_DEFAULT = 65;

    const USER_OS_IOS = 'iOS';
    const USER_OS_ANDROID = 'Android';

    const WIRELESS_CARRIER = 'Wifi';

    const DEVICE_PLATFORM_MOBILE = 'mobile';
    const DEVICE_PLATFORM_DESKTOP = 'desktop';

    const PUBLISHER_PLATFORM_FACEBOOK = 'facebook';
    const PUBLISHER_PLATFORM_INSTAGRAM = 'instagram';
    const PUBLISHER_PLATFORM_AUDIENCENETWORK = 'audience_network';

    const FACEBOOK_POSITION_FEED = 'feed';
    const FACEBOOK_POSITION_RIGHTHAND = 'right_hand_column';

    const RELATIONSHIP_STATUSE_SINGLE = 1;
    const RELATIONSHIP_STATUSE_IN_RELATIONSHIP = 2;
    const RELATIONSHIP_STATUSE_MARRIED = 3;
    const RELATIONSHIP_STATUSE_ENGAGED = 4;
    const RELATIONSHIP_STATUSE_NOT_SPECIFIED = 6;
    const RELATIONSHIP_STATUSE_CIVILUNION = 7;
    const RELATIONSHIP_STATUSE_DOMESTIC_PARTNERSHIP = 8;
    const RELATIONSHIP_STATUSE_OPEN_RELATIONSHIP = 9;
    const RELATIONSHIP_STATUSE_COMPLICATED = 10;
    const RELATIONSHIP_STATUSE_SEPARATED = 11;
    const RELATIONSHIP_STATUSE_DIVORCED = 12;
    const RELATIONSHIP_STATUSE_WIDOWED = 13;

    const INTERESTED_IN_MEN = 1;
    const INTERESTED_IN_WOMEN = 2;
    const INTERESTED_IN_MEN_WOMEN = 3;
    const INTERESTED_IN_NOT_SEPC = 4;

    const EDUCATION_STATUSES_HIGH_SCHOOL = 1;
    const EDUCATION_STATUSES_UNDERGRAD = 2;
    const EDUCATION_STATUSES_ALUM = 3;
    const EDUCATION_STATUSES_HIGH_SCHOOL_GRAD = 4;
    const EDUCATION_STATUSES_SOME_COLLEGE = 5;
    const EDUCATION_STATUSES_ASSOCIATE_DEGREE =6;
    const EDUCATION_STATUSES_IN_GRAD_SCHOOL = 7;
    const EDUCATION_STATUSES_SOME_GRAD_SCHOOL = 8;
    const EDUCATION_STATUSES_MASTER_DEGREE = 9;
    const EDUCATION_STATUSES_PROFESSIONAL_DEGREE = 10;
    const EDUCATION_STATUSES_DOCTORATE_DEGREE = 11;
    const EDUCATION_STATUSES_UNSPECIFIED = 12;
    const EDUCATION_STATUSES_SOME_HIGH_SCHOOL = 13;

    const COLLEGE_YEAR_MIN_LIMIT = 1980;
    const EDUCATION_MAJOR_COUNT_LIMIT = 200;
    const WORK_EMPLOYER_COUNT_LIMIT = 200;
    const WORK_POSITION_COUNT_LIMIT = 200;

    const TARGETING_COMMON_ID = 'id';

    const COUNTRY_COUNT_LIMIT = 25;
    const REGION_COUNT_LIMIT = 200;
    const CITY_COUNT_LIMIT = 250;
    const CITY_RADIUS_MIN_MILE_LIMIT = 10;
    const CITY_RADIUS_MAX_MILE_LIMIT = 50;
    const CITY_RADIUS_MIN_KILOMETER_LIMIT = 17;
    const CITY_RADIUS_MAX_KILOMETER_LIMIT = 80;
    const ZIPS_COUNT_LIMIT = 2500;
    const CUSTOM_LOCATION_COUNT_LIMIT = 200;
    const CUSTOM_LOCATION_MIN_MILE_LIMIT = 0.62;
    const CUSTOM_LOCATION_MAX_MILE_LIMIT = 50;
    const CUSTOM_LOCATION_MIN_KILOMETER_LIMIT = 1;
    const CUSTOM_LOCATION_MAX_KILOMETER_LIMIT = 80;
    const GEO_MARKET_COUNT_LIMIT = 2500;
    const LOCALE_LANGUAGE_COUNT_LIMIT = 50;

}