<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9d8a7b2945620d445394383ccfd5b5e1
{
    public static $files = array (
        'cb4e5a3b92883c2abbbd5cf62df19cae' => __DIR__ . '/../..' . '/init/DBServiceInit.php',
    );

    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DBService\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DBService\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9d8a7b2945620d445394383ccfd5b5e1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9d8a7b2945620d445394383ccfd5b5e1::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
