<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'f38f5de8b305c666fc7efb30c07ad0d3' => $baseDir . '/init/DuplicateAdInit.php',
);
